model_name: mpi_v3
data_dir: Data/v3
batch_size: 60
seed: 0
best_acc:
  name: mse
  value: 99.
best_weight_path: null
epochs: 300
gpu: '0'

init_lr: 0.0001
scheduler:
  milestones:
  - 20
  - 60
  - 120
  gamma: 0.1
log_dir: None
max_early_stop: 40
img_keys:
- AOD047
- AOD055
- BLUE
- EVI
- GREEN
- NDVI
- NIGHTLIGHTS
- NIR
- RED
- SWIR1
- SWIR2
- TEMP1
- age_struct_child
- age_struct_middle
- age_struct_old
- age_struct_young
- aspect
- elevation
- male
- osm
- pr
- slope
- tmmn
- tmmx
- viirs_v2
num_keys:
- DHSCLUST1
- tmm_sum
- Households_num
- Individual_num
- Number of Households2
- area
- death_num
- building_area
- burnedCount
- conflict_num
- death_num
- place_num
- poi_num
- pr_sum
- water
- DHSCLUST1
label_keys:
- MPI3_fixed
- H
- A
- education
- health
- Living Standards
pos_keys:
- lat
- lon
- name
restore_weight: null

