model_name: v4_gp
data_dir: Data/v4
run_gp: 0
batch_size: 60
seed: 0
best_acc: 99.
best_weight_path: null
best_gp_path: null
epochs: 300
gpu: '0'

init_lr: 0.001
scheduler:
  milestones:
  - 20
  - 60
  - 120
  gamma: 0.1
log_dir: None
max_early_stop: 40
img_keys:
- AOD047
- AOD055
- BLUE
- EVI
- GREEN
- NDVI
- NIGHTLIGHTS
- NIR
- RED
- SWIR1
- SWIR2
- TEMP1
- age_struct_child
- age_struct_middle
- age_struct_old
- age_struct_young
- aspect
- elevation
- male
- osm
- pr
- slope
- tmmn
- tmmx
- viirs_v2
num_keys:
- DHSCLUST1
- tmm_sum
- Households_num
- Individual_num
- Number of Households2
- area
- death_num
- building_area
- burnedCount
- conflict_num
- death_num
- place_num
- poi_num
- pr_sum
- water
- DHSCLUST1
- lat
- lon
- year
label_keys:
- MPI3_fixed
- H
- A
- education
- health
- Living Standards
- lat
- lon
- year

restore_weight: null

