M:
  model: swint
  img_size: 224
  batch_size: 40
  seed: 10
  best_acc: -99
  best_weight_path: null
  epochs: 500
  crt_epoch: 1
  device: 0
  init_lr: 0.0001
  log_dir: Logs
  max_early_stop: 10
  restore_weight: null
  k: 5
  scheduler:
    milestones:
      - 100
    gamma: 0.1
    
D:
  source: Data/nga_mpi.csv
  data_dir: Data/origin224
  img_keys:
    - BLUE
    - GREEN
    - NIR
    - RED
    - SWIR2
    - TEMP1
    - age_struct_child
    - age_struct_young
    - age_struct_middle
    - age_struct_old
    - elevation
    - famale
    - male
    - pr
    - tmmn
    - tmmx
    - viirs_v2
    # 重建
  deprecated_keys:
    - NDVI
    - slope

  num_keys:
    - death_num
    - building_area
    - burnedCount
    - conflict_num
    - place_num
    - poi_num
    # - water
    - lat
    - lon
    - year
  label_keys:
    - MPI3_fixed
    - lat
    - lon
    - poi_num
    - building_area
    - year

  indicator_keys:
    - Child mortality
    - Nutrition
    - School attendance
    - Years of schooling
    - Electricity
    - Drinking water
    - Sanitation
    - Housing
    - Cooking fuel
    - Assets

GP:
  is_gp: 1
  best_gp_path: null
  sigma: 1
  r_loc: 2.5 
  r_year: 10
  r_poi: 40
  r_building: 0.01
  sigma_e: 0.32
  sigma_b: 0.01
  
FDS:
  is_fds: 0


