M:
  model: swint
  img_size: 224
  batch_size: 50
  seed: 10
  best_acc: 99
  best_weight_path: null
  epochs: 1000
  crt_epoch: 1
  device: 0
  init_lr: 0.001
  log_dir: Logs
  max_early_stop: 10
  restore_weight: null
  k: 5
  scheduler:
    milestones:
      - 10
      - 30
      - 80
    gamma: 0.1
    
D:
  source: Data/nga_mpi.csv
  data_dir: Data/origin224
  img_keys:
    - BLUE
    - GREEN
    - NIR
    - RED
    - SWIR2
    - TEMP1
    - age_struct_child
    - age_struct_young
    - age_struct_middle
    - age_struct_old
    - elevation
    - famale
    - male
    - pr
    - tmmn
    - tmmx
    - viirs_v2
  deprecated_keys:
    - NDVI
    - slope

  num_keys:
    - tmm_sum
    - area
    - death_num
    - building_area
    - burnedCount
    - conflict_num
    - place_num
    - poi_num
    # - water
    - lat
    - lon
    - year
  label_keys:
    - MPI3_fixed
    - lat
    - lon
    - year

  indicator_keys:
    - Child mortality
    - Nutrition
    - School attendance
    - Years of schooling
    - Electricity
    - Drinking water
    - Sanitation
    - Housing
    - Cooking fuel
    - Assets

GP:
  is_gp: 0
  best_gp_path: null

VIT:
  is_vit: 0
  vit_dim: 128
  vit_depth: 2
  vit_heads: 3
  vit_mlp_dim: 128
  vit_dropout: 0.0

FDS:
  is_fds: 1